"""Initial revision

Revision ID: 2eedfd2689c3
Revises: b441e85b2155
Create Date: 2025-03-22 22:08:23.000228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2eedfd2689c3'
down_revision: Union[str, None] = 'b441e85b2155'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tickets',
    sa.Column('namesurname', sa.Text(), nullable=False),
    sa.Column('year', sa.Text(), nullable=False),
    sa.Column('tel_number', sa.String(), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['purchases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('purchases', 'payment_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchases', sa.Column('payment_id', sa.VARCHAR(), nullable=False))
    op.drop_table('tickets')
    # ### end Alembic commands ###
